name: mc_survey
description: A MiniCampus Survey module
version: 0.0.1
homepage: https://github.com/DonnC-Lab/mini_campus
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_vector_icons: ^1.0.0

  # components
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  keyboard_actions: ^3.4.7
  animate_do: ^2.1.0
  modal_bottom_sheet: ^2.0.1

  # state management
  flutter_riverpod: ^2.0.0-dev.4

  # notification
  flash: ^2.0.3+2

  # utilities
  freezed_annotation: ^1.1.0
  relative_scale: ^2.0.0

  # misc
  json_annotation: ^4.4.0

  # browser
  flutter_web_browser: ^0.17.1

  # custom mc libs
  mini_campus_core:
    git: 
      url: https://github.com/DonnC-Lab/mini_campus_core.git
      ref: main

  mini_campus_core_libs:
    git: 
      url: https://github.com/DonnC-Lab/mini_campus_core_libs.git 
      ref: main

  mc_core_constants:
    git: 
      url: https://github.com/DonnC-Lab/mc_core_constants.git
      ref: main # branch name

  mini_campus_core_components:
    git:
      url: https://github.com/DonnC-Lab/mini_campus_core_components.git
      ref: main

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
